### ISSUE TITLE
interval stuck on 1D

### ISSUE THREAD

**Issue by skedzior** [JorrinKievit/react-ts-tradingview-widgets#1]
doesn't seem the interval prop is persisting when passed in, all charts load as 1D

**Comment by JorrinKievit** [comment]
Hey, thanks for reporting!

The reason this happened is because interval and range can not both be defined. I had default values set for both. Fixed this in the new release (v1.0.4). When a range is added as a prop, the chart will load with the given range instead of the default interval.
