### ISSUE TITLE
Add feature to customize Copyright's text and link

### ISSUE THREAD

**Issue by Kikky** [JorrinKievit/react-ts-tradingview-widgets#11]
Hello!

Can you, please, make Copyright's text and link (anchor and url) to be customizable?

We need this to include affiliate link to TW website and to customize captions of the charts a little bit.

I can make PR if necessary. Thanks in advance!

**Comment by JorrinKievit** [comment]
Is this not what you are looking for? https://tradingview-widgets.jorrinkievit.xyz/docs/Copyright%20attribute
