### ISSUE TITLE
How react uses tradingview proxy

### ISSUE THREAD

**Issue by OnlyDawn** [JorrinKievit/react-ts-tradingview-widgets#12]
Error handling response: Error: Blocked a frame with origin "https://s.tradingview.com" from accessing a cross-origin frame.
    at tryShowingMateBar (eval at success (chrome-extension://ihmgiclibbndffejedjimfjmfoabpcke/src/kernel/kernel.js:233:37), <anonymous>:5428:57)
    at eval (eval at success (chrome-extension://ihmgiclibbndffejedjimfjmfoabpcke/src/kernel/kernel.js:233:37), <anonymous>:153:17)
    at eval (eval at success (chrome-extension://ihmgiclibbndffejedjimfjmfoabpcke/src/kernel/kernel.js:233:37), <anonymous>:108:27)
?frameElementId=tradingview_41b54&symbol=AAPL&interval=D&hidetoptoolbar=1&hidesidetoolbar=0&symboledit=1&saveimage=0&toolbarbg=f1f3f6&studies=%5B%5D&theme=light&style=3&timezone=exchange&withdateranges=1&studies_overrides=%7B%7D&overrides=%7B%7D&enabled_features=%5B%5D&disabled_features=%5B%5D&locale=zh_CN&utm_source=localhost&utm_medium=widget&utm_campaign=chart&utm_term=AAPL:14 WebSocket connection to 'wss://widgetdata.tradingview.com/socket.io/websocket?from=widgetembed%2F&date=2022_09_07-11_27' failed:

**Comment by OnlyDawn** [comment]
Hi, I have the above problem

**Comment by JorrinKievit** [comment]
Seems to be blocked by an extension, try in ingocnito?

**Comment by OnlyDawn** [comment]
Sorry, I don't quite understand what to do

**Comment by OnlyDawn** [comment]
Referrer Policy: strict-origin-when-cross-origin

**Comment by JorrinKievit** [comment]
One of your browser extensions seem to block the iframes. Try to open your project in a private window ->

<img width="374" alt="image" src="https://user-images.githubusercontent.com/43169049/188883683-4f3e1015-08fa-4cac-89b4-1992c9aa513e.png">

(mine is in dutch but third option)

**Comment by OnlyDawn** [comment]
I've tried, but it still doesn't work. The console is OK, but the network reports an error: refer policy: strict origin when cross origin

**Comment by OnlyDawn** [comment]
Wow, that's ok

But under normal circumstances, it still can't be opened

**Comment by JorrinKievit** [comment]
Can you specify? Is it working in the private window?

**Comment by OnlyDawn** [comment]
> private window?

Yes, it can be opened in privacy mode

**Comment by JorrinKievit** [comment]
I'm not sure what the s.tradingview.com domain is used for, since the charts are still fully functional. But unfortunately I cannot change another extensions behaviour and the underlying issue should be with the Mate Translator extension

**Comment by OnlyDawn** [comment]
Yes, the success is indeed a problem of mate translator extension. Thank you very much.
