### ISSUE TITLE
Support for custom lines

### ISSUE THREAD

**Issue by zhe-t** [JorrinKievit/react-ts-tradingview-widgets#13]
Hi! Is it possible to add a custom line to the trading view chart? I.e. for an order

**Comment by JorrinKievit** [comment]
Hmmm not sure, does not seem to be documented by the TradingView team

**Comment by JorrinKievit** [comment]
After scrolling through https://s3.tradingview.com/tv.js I don't think it's possible doing programmaticly

**Comment by JorrinKievit** [comment]
You could do it with this though -> https://github.com/tradingview/lightweight-charts
