### ISSUE TITLE
MarketData Component PROPS. width: number | string  has been mistakenly configured to width: number | number

### ISSUE THREAD

**Issue by temiye18** [JorrinKievit/react-ts-tradingview-widgets#16]
The type of width prop which is to be passed optionally to the MarketData component has been explicitly configured to take only a value of type number | number instead of union type number | string. please kindly look into it. 

PS: This is a wonderful package.

**Comment by temiye18** [comment]
![trading](https://user-images.githubusercontent.com/39435825/205214274-77bf903f-7c36-4331-a42f-4da5e2172741.png)


Likewise, there is an error in the official documentation. the MarketData component is expected to be an optional symbolsGroups prop and not "symbolsGroup" I had to read the source code before I found it was a typo error on the docs website. in summary, the type of width should be  changed from width?: number | number;    to   width?: number | string, and the type of height from  height?: number | number  to    height?: number | string;

**Comment by JorrinKievit** [comment]
Oopsie, will update!
