### ISSUE TITLE
Avoid console's errors

### ISSUE THREAD

**Issue by solncebro** [JorrinKievit/react-ts-tradingview-widgets#19]
Hello!
I am using AdvancedRealTimeChart in 2 places on my page. But I have 3 console errors per instance. It happens again every time the page is rendered
Do you know how to avoid these errors in the console? 

![localhost:3000 2022-12-09 22-44-07](https://user-images.githubusercontent.com/42976880/206728299-5cac895f-a5e3-4ac9-9340-7eecdc91fad4.png)

**Comment by JorrinKievit** [comment]
What browser? Also in incognito? I'm pretty sure all of these are just for tracking purposes (gtag/tradingview telemetry) which are blocked by extensions or browsers like Brave. They don't actually break the widgets or am I mistaken?

**Comment by JorrinKievit** [comment]
Closed due to inactivity
