### ISSUE TITLE
Widget Settings Parse Error.

### ISSUE THREAD

**Issue by tielushko** [JorrinKievit/react-ts-tradingview-widgets#2]
Hi Jorrin! 

First of all, big thank you for this library you wrote, very cool to see the implementation for React. 

I was wondering, I have encountered the error as following: 

![image](https://user-images.githubusercontent.com/46033508/133138142-8c50e426-bfb3-4e06-bf96-93ab7d19e99b.png)

The only thing I have done in my project is installed the library, and added the component. When passing in different props, such as dark theme, I am stuck with the widget resetting itself to default. Here is my return statement:

![image](https://user-images.githubusercontent.com/46033508/133138424-ade9cd98-5152-4282-b283-1ba3c7769ab2.png)

Yet here's how the component looks:
![image](https://user-images.githubusercontent.com/46033508/133138498-c0a6f988-0bea-4ae4-bbe0-5d22084731bb.png)

I would appreciate your advice!

Best, 
Oleg

**Comment by JorrinKievit** [comment]
Hey, thanks for reporting!

Shouldn't have rushed the new release out when I did. Fixed the first issue and created a new one ;). Should be fixed on version v1.0.5!

**Comment by tielushko** [comment]
Cheers man! Thanks for your quick reply! let me fetch the new version and check out the updates.
