### ISSUE TITLE
Chart reverts to default stock symbol

### ISSUE THREAD

**Issue by tylrk** [JorrinKievit/react-ts-tradingview-widgets#20]
Hello. I was wondering if there is any way to keep the chart from reverting to the default stock symbol when I change the theme of the chart. In my following code, when I switch from dark to light mode, my chart reverts back to the AAPL chart. Any help is much appreciated!

```
import React, { useState } from "react";
import "./App.css";
import Navbar from "./components/Navbar";
import {
  AdvancedRealTimeChart,
  ColorTheme,
} from "react-ts-tradingview-widgets";

const App: React.FC = (props) => {
  const [theme, setTheme] = useState<ColorTheme>("light");

  function changeTheme(): void {
    setTheme(theme === "light" ? "dark" : "light");
  }

  return (
    <>
      <Navbar theme={theme} changeTheme={changeTheme} />
      <div className="chart">
        <AdvancedRealTimeChart theme={theme} />
      </div>
    </>
  );
};

export default App;
```

**Comment by JorrinKievit** [comment]
Now that I think about it, you could technically get the iframe, retrieve the symbol from the URL and add that as default symbol when changing theme 🤔

**Comment by tylrk** [comment]
Yea, I tried looking through the JS as well, and I tried using various methods to get it to work through state. However, that was quite cumbersome and ended up as a dead end. 

I appreciate the response though. This is still a great package. Thanks for putting this all together and sharing it!
