### ISSUE TITLE
Reload every time states change

### ISSUE THREAD

**Issue by SaeedPoureshghi** [JorrinKievit/react-ts-tradingview-widgets#22]
Hi;
Because of re-rendering the page when any state changed it is refreshing too. I used websocket to update data on page. on every data update trying to refresh widgets and sucks.

**Comment by SaeedPoureshghi** [comment]
Solved before!

**Comment by JorrinKievit** [comment]
How did you solve it? 🙂

**Comment by SaeedPoureshghi** [comment]
check sandbox code
[https://codesandbox.io/embed/gifted-kepler-gtso10?fontsize=14&hidenavigation=1&theme=dark](url)

**Comment by SaeedPoureshghi** [comment]
using memo:

widget.js

```
import React from "react";
import { memo } from "react";
import { TechnicalAnalysis } from "react-ts-tradingview-widgets";
const Widget = (props) => {
  return <TechnicalAnalysis symbol="BINANCE:BTCUSDT" colorTheme="light" />;
};

export default memo(Widget);

```

reference : https://www.w3schools.com/react/react_memo.asp
