### ISSUE TITLE
Drawing on the chart generated

### ISSUE THREAD

**Issue by DENNIS-CODES** [JorrinKievit/react-ts-tradingview-widgets#24]
hello am trying to draw on the chart using react is there a tool i can use to draw horizontal line using react on the trading view chart

**Comment by JorrinKievit** [comment]
Can you specify? You are able to draw lines/all kinds of stuff on the AdvancedRealTimeChart

**Comment by DENNIS-CODES** [comment]
I need to draw horizontal lines in AdvancedRealTimeChart using code ie in react, is there a way to draw the lines by specifying the parameters on the widget, if they are no way, can I control a line drawn using the tools bar, such as adjusting the position of the line by moving up or down using react

**Comment by DENNIS-CODES** [comment]
thank you this was helpful, but consider adding the features on the widget in the future

**Comment by JorrinKievit** [comment]
TradingView simply does not offer these features. Out of my reach unfortunately
