### ISSUE TITLE
Custom redirect in TicketTape

### ISSUE THREAD

**Issue by CopsLikeDonuts** [JorrinKievit/react-ts-tradingview-widgets#34]
Hi all! Is there any possibility to make custom redirect after symbol is clicked in widget? For example, I click on Bitcoin and it redirects me to https://my-app.com/bitcoin instead of Trading View Bitcoin page overview.

**Comment by JorrinKievit** [comment]
Doesn't seem like TradingView supports it 😢 

https://www.tradingview.com/widget/ticker/
