### ISSUE TITLE
Cannot set chartType of the Symbol Overview Widget

### ISSUE THREAD

**Issue by finetech-ai** [JorrinKievit/react-ts-tradingview-widgets#4]
On the TradingView Symbol Overview Widget iframe page, we can change the "chartType" setting but in this React wrapper it is not supported, will this be supported in the future?

![image](https://user-images.githubusercontent.com/81511074/133757007-afb586f3-86b5-4730-b1e7-b8fd39463d53.png)

Thanks in advance!

**Comment by JorrinKievit** [comment]
Seems like the widget has been updated since the last time I implemented it. I'll work on an update right now!

**Comment by JorrinKievit** [comment]
Updated the widget, not publishing it yet because I noticed other widgets are outdated too. After I'm done updating the other widgets I will publish the new version.

**Comment by JorrinKievit** [comment]
Hey, just released v1.0.6. Updating the package should fix your issue. Let me know if any other issues occur!

**Comment by finetech-ai** [comment]
Thanks for the rapid response, much appreciated!

I copied exactly the sample code for the SymbolOverview chart from the documentation site and I cannot get the chart working, this is the error being raised in the console

Let me know if you need further information from me, thanks!

![image](https://user-images.githubusercontent.com/81511074/133978597-836e85f9-502c-4e31-a7da-670c3be2c51b.png)

**Comment by JorrinKievit** [comment]
Hey, fixed in v1.0.8. Apparently document queryselectors do not like to query on Math.random ids :). Apologies for the inconvenience.

**Comment by finetech-ai** [comment]
Thank you, it works now!
