### ISSUE TITLE
Is there anyway to know the ticker didn't exists ?

### ISSUE THREAD

**Issue by erwan-joly** [JorrinKievit/react-ts-tradingview-widgets#40]
Hello, when searching for a ticker that does not exists on AdvancedRealTimeChart we get this error logged in the console:
2023-09-12T06:40:44.105Z:Chart.LegendWidget:Quote snapshot error: Quotes snapshot is not received

Is there a way to know the ticker does not exists ? Additionally it would be nice to have an option not to log that error.
My goal here is to display something else when the ticker does not exists.

I currently look at the message event tv-widget-no-data but it is also sent when the ticker does exists but the data is only available on the website example EURONEXT:SOP

Thanks

**Comment by JorrinKievit** [comment]
As far as i know there is no way of communicating with the embed once it's initialized. I can't control the logging either since its an iframe and the source code that is logging that error is externally from tradingview
