### ISSUE TITLE
refactor: Lack of `LoadingScreenOptions` Customization Capabilities

### ISSUE THREAD

**Issue by mohadeseh-mousavisaeid** [JorrinKievit/react-ts-tradingview-widgets#41]
> Hello, 
> First things first, I have to thank you for this powerful library.
> I have faced with the issue of customizing the loading-screen `backgroundColor` and `foregroundColor` while working with `AdvancedRealTimeChart`.

### Description:

**LoadingScreenOptions**, which is provided in the TradingView Widget Constructor, has not been considered in type of 
`AdvancedRealTimeChartProps`.

### API Reference:

[https://www.tradingview.com/charting-library-docs/latest/api/interfaces/Charting_Library.LoadingScreenOptions](url)
[https://www.tradingview.com/charting-library-docs/latest/core_concepts/Widget-Constructor/](url)

**Comment by JorrinKievit** [comment]
Hey. I think this is a different library compared to the widget -> https://www.tradingview.com/widget/advanced-chart/

This library simply wraps the widgets. I read the docs of this library, and it seems that this charting library can only be obtained by sending a request trough a form? I can experiment and see if some of these props in the docs overlap with the advanced chart widget, but the widget documentation does not mention them
