### ISSUE TITLE
Subscribing to latest price

### ISSUE THREAD

**Issue by SolidiTea** [JorrinKievit/react-ts-tradingview-widgets#46]
The component itself works great, good job !

Is there a way to subscribe to the prices displayed in the chart, most importantly the latest price ? 

This is critical to allow users to work with the most up to date data and prevent two "sources of truth"

**Comment by JorrinKievit** [comment]
Unfortunately not a functionality the tradingview widgets provide. There is no way of interacting with the charts after initialization. For more customized charts, tradingview offers this -> https://www.tradingview.com/lightweight-charts/
