### ISSUE TITLE
Add attribution link below the widgets

### ISSUE THREAD

**Issue by mayrsascha** [JorrinKievit/react-ts-tradingview-widgets#5]
I was in contact with the Tradingview support and they checked my site which uses this library. They mentioned that we shouldn't use their widgets without the attribution at the bottom of the widget (not the one inside the widget) as seen here:

![image](https://user-images.githubusercontent.com/29578226/152363131-feb48765-0646-4ebf-9b93-2f4d8117f41a.png)

It is not showing on the demo page as well, so I guess this is not showing on purpose?

**Comment by JorrinKievit** [comment]
Hey, also just got in contact with TradingView. I was not aware the attribution was required. I think I will be integrating the attribution in the components, with customizable styling.

**Comment by JorrinKievit** [comment]
Fixed in 1.0.9

**Comment by 0xsol1id** [comment]
I know this issue is closed already, but I reached out tradingview for the exact same issue, and they told me something different. They sended me a bunch of PNGs to implement into my website (for example into the footer), if I want to delete the attribution line, so it would be nice to implement that the attributtion is switchable.

**Comment by JorrinKievit** [comment]
Hm that's interesting. They indeed contacted me and asked me to include the attribute under the widget. Which is why I only added styling customization so you could position it anywhere below the chart 🤔

**Comment by 0xsol1id** [comment]
Ok, maybe they decide differently on a case-by-case basis. you have built a framework to use the widgets, maybe they rate it different than a website. Or maybe it was also about the fact that it has to appear in the framework at all and must not be omitted from the outset.

**Comment by JorrinKievit** [comment]
Ye I assume the last part, could contact for more clarification

**Comment by emorling** [comment]
> I know this issue is closed already, but I reached out tradingview for the exact same issue, and they told me something different. They sended me a bunch of PNGs to implement into my website (for example into the footer), if I want to delete the attribution line, so it would be nice to implement that the attributtion is switchable. That´s what they wrote (google-translated):
> 
> We are very pleased that you have integrated our widgets. On the chart page, the logo must have do_follow signature. See screenshot in the attachment. I also attach the logos. On the page of the Frankfurt Stock Exchange, below footer is a great example: https://www.boerse-frankfurt.de Let us know if you have any further questions. Thank you in advance.

Can you attach the screenshot they sent you, please? 🙏🏽
