### ISSUE TITLE
When changing advanced real time chart symbol dynamically the chart does not reload

### ISSUE THREAD

**Issue by amogh0503** [JorrinKievit/react-ts-tradingview-widgets#57]
I am trying to change symbol `<AdvancedRealTimeChart symbol={symbol} interval="W" />` where symbol changes with page number selected but the chart keeps showing 1st symbol only

**Comment by abidr** [comment]
I have also faced this issue. Downgrading to **1.0.16** fixed the issue for me.

**Comment by JorrinKievit** [comment]
Should be fixed in 1.2.4
