### ISSUE TITLE
Tradingview Widget background issue on Theme Switch in Next.js 14 Application

### ISSUE THREAD

**Issue by emre-turan** [JorrinKievit/react-ts-tradingview-widgets#60]
Hello and thank you for maintaining this wonderful repository. I've been integrating widgets into a Next.js 14 project and have come across an issue related to theme compatibility that I hope to get some assistance with.

In my project, I've configured the widget with the isTransparent setting enabled, aiming to harmonize the widget's background with my application's theme dynamically. This setup performs flawlessly under light mode, aligning perfectly with my expectations.

However, I encounter a challenge when the application initializes in dark mode or when switching to dark mode from light mode. Despite the expectation for isTransparent to adapt, the widget persists with a default white background, disregarding the theme switch in the web application.

This issue seems to persist across theme changes, and I'm curious if this is a known issue or if there are recommended approaches to ensure the widget's background remains transparent and consistent with the active theme setting.

Technical Context:

Framework: Next.js 14
Theme Management: Next-theme
Language: TypeScript

I would greatly appreciate any insights, suggestions, or solutions to ensure the widget's background transparency aligns with the dynamic theme changes in the application.

**Comment by JorrinKievit** [comment]
What does your code look like? The widget should rerender if the props changes

**Comment by emre-turan** [comment]
There may be an incompatibility with the next-theme package. I think the problem is directly related to the widget. I moved the topic to them.
