### ISSUE TITLE
How to implent "disabled_features" keyword into the library

### ISSUE THREAD

**Issue by 0xsol1id** [JorrinKievit/react-ts-tradingview-widgets#8]
Hi,
I´m rebuilding my widget-project in react using your library, but I´m struggling to implement the "disabled_features" keyword into it.
In HTML and vanilla JS I used to call it like this:

```
new TradingView.widget(    {
        "autosize": true,
        "symbol": tickerID,
        "interval": interval,
        "range": range,
        "timezone": "Etc/UTC",
        "theme": "dark",
        "style": "1",
        "locale": "de_DE",
        disabled_features: ["create_volume_indicator_by_default", "control_bar"],
        "enable_publishing": false,
        "hide_top_toolbar": true,
    }    )
```
It is necessary, because with this option enabled it won´t show the volume indicator and the control bar at start, which both is really annoying especially at small charts. In HTML it works out of the box, but I tried to implement it into your library just like the other types, but it seems like it doesn´t do anything at all. 

Any idea why and how to accomplish that? Am I missing something in relation to react and typescript?
Greetz

**Comment by JorrinKievit** [comment]
Hey, I was not aware this was a feature at all. Is this documented anywhere? Since I do not see anything related to this on their [widget page](https://www.tradingview.com/widget/advanced-chart/).

**Comment by JorrinKievit** [comment]
Yes I already added it, just a bit busy right now so expect a new version in the upcoming days :)

**Comment by JorrinKievit** [comment]
published ;)
